### ISSUE TITLE
Bug in importing annotations

### ISSUE THREAD

**Issue by lukaswozniak** [jveitchmichaelis/deeplabel#27] opened 2021-10-01 14:24 UTC
After clicking "Import Labels" with configuration:
![image](https://user-images.githubusercontent.com/43893492/135636029-384debec-367a-4aa4-9e3f-7644bdb7da92.png)

Loading of images starts:
![image](https://user-images.githubusercontent.com/43893492/135636178-5ea026df-afa2-4785-a117-bd96333a7fa6.png)

But after it is finished I get following error:
![image](https://user-images.githubusercontent.com/43893492/135636282-d59a91bb-3c31-4374-bb0b-97b3a54eb0a9.png)

Please help

**Comment by jveitchmichaelis** [comment] 2021-10-01 15:52
OK, this is probably a quick fix. Looks like a bug in absolute/relative
path resolution

**Comment by jveitchmichaelis** [comment] 2021-10-01 16:12
The issue is probably that your image list contains relative paths, and
deeplabel doesn't know what they're relative to. I could add an option to
provide an image folder, but generally darknet image lists can contain
multiple folders.

Can you change your paths to absolute? That should also work with darknet
still.

**Comment by lukaswozniak** [comment] 2021-10-01 16:24
Could those be relative to my .lbldb project file?
Changing paths to absolute is possible but not preferred - when collaborating on the project absolute paths are different for each person.

**Comment by jveitchmichaelis** [comment] 2021-10-01 16:44
We could assume paths are relative to the db file, but that seems
unnecessarily restrictive.

I think the simplest solution for now is to specify an optional root folder
that the image paths are relative to. I think even in the case where
someone had multiple folders (for example), the root path for the image
list should be the same.

For the same reason you mention, deeplabel doesn't store absolute paths.

**Comment by lukaswozniak** [comment] 2021-10-01 17:00
Sure its even better to be able to specify it. Just thought .lbldb location could be good default for that root folder.

**Comment by jveitchmichaelis** [comment] 2021-10-01 20:49
Pushed a quick fix for this, I'll upload a release later today (https://github.com/jveitchmichaelis/deeplabel/commit/7b76cf60820654b126162e0ed39813f3a73a18ac and https://github.com/jveitchmichaelis/deeplabel/commit/5fd441ced2265d8d52db97fdc18b6e40ebbb61a8)

**Comment by lukaswozniak** [comment] 2021-10-01 20:57
Thanks! I will check it tomorrow.

**Comment by lukaswozniak** [comment] 2021-10-01 21:12
I managed to compile it, unfortunately it's still not working. Fails with the exact same error:

![image](https://user-images.githubusercontent.com/43893492/135686658-025f63f1-361b-4053-b278-bd8ef13297a5.png)

**Comment by jveitchmichaelis** [comment] 2021-10-01 21:19
Weird, I don't know why it's prepending the label database path onto the images. You can see that it's adding the relative path as expected, but for some reason it's also adding `deeplabel.lbldb` inbetween. That's definitely not in your train.txt? The code to resolve the path is very simple:

```
image_path = QFileInfo(QDir(root_folder).absoluteFilePath(image_path)).canonicalFilePath();
```

Where the image path is read from the text file. I don't know how the database filename (and only the filename) would get in there.

EDIT: Oh OK I see it's a bit confusing, the labeldb file is also in the same folder? So maybe it's not actually prepending the relative path properly. I did test this locally and it seemed fine.

**Comment by lukaswozniak** [comment] 2021-10-01 21:21
While loading the path is ok:

![image](https://user-images.githubusercontent.com/43893492/135687434-146061fa-f354-439e-acdc-eca32393f95a.png)

After loading when it tries to open the first image in the bottom status bar the path is wrong:
![image](https://user-images.githubusercontent.com/43893492/135687492-794b4a62-384c-470a-a856-4c6bcc3d2107.png)

And then the error shows up in console.

**Comment by lukaswozniak** [comment] 2021-10-01 21:33
Ah yes, I moved the .lbldb to the data folder, BUT it shouldn't matter now right?
Now I moved the .lbldb back to the root directory, and it is working correctly 👍

**Comment by jveitchmichaelis** [comment] 2021-10-01 21:39
Yeah it shouldn't make a difference where the lbldb is - all the code is doing is taking the path you provided and concatenating it with the paths in your train.txt file.

**Remember that deeplabel also stores image paths relative to the database location**, so if you move the lbldb file, the path to your images will be wrong. Probably a feature to add is the ability to update the root folder of the label database as well.

**Comment by lukaswozniak** [comment] 2021-10-01 21:40
Yes

**Closed as completed** 2021-10-01 21:44 UTC
